In [8]:
import pandas as pd
import numpy as np
from librerias.ConexionBDD import ConexionMySQL
from sqlalchemy import create_engine
import sqlite3
import os

In [9]:
# Ruta donde se guardaran los archivos tratados segun el caso de estudio
ruta_guardado_caso1 = os.getcwd()+"/Archivos/Base_de_datos/Caso estudio 1/"
ruta_guardado_caso6 = os.getcwd()+"/Archivos/Base_de_datos/Caso estudio 6/"

# Rutas para leer los archivos descargados de una fuente de datos segun los casos de estudio
ruta_caso1 =os.getcwd()+"/Archivos/Caso de estudio 1/"
ruta_caso6 =os.getcwd()+"/Archivos/Caso de estudio 6/"

_Modificar los archivos_

_Caso 1_

In [10]:
# Cargar los datos del archivo para el caso 1
Datos = pd.read_csv(ruta_caso1+"social media influencers - Tiktok sep 2022.csv", delimiter=",", index_col="S.no")
Datos.isnull().sum()

Tiktoker name    0
Tiktok name      1
Subscribers      0
Views avg.       0
Likes avg.       0
Comments avg.    0
Shares avg.      0
dtype: int64

In [11]:
Datos.head(17)

,Tiktoker name,Tiktok name,Subscribers,Views avg.,Likes avg.,Comments avg.,Shares avg.
S.no,,,,,,,
1,jypestraykids,Stray Kids,13.8M,6.4M,2.3M,50.2K,34.2K
2,khaby.lame,Khabane lame,149.2M,17.3M,2.3M,15.2K,8.7K
3,scarlettsspam2,scarlett,2.1M,17.9M,845.8K,53.9K,6.3K
4,addisonre,Addison Rae,88.7M,22M,906.6K,7.6K,26.2K
5,belindatok,Belinda,4.8M,14.2M,1.5M,14.5K,15.3K
6,onwardwanna,WannaðŸ¥Š,7.5M,12M,2M,20.4K,4.2K
7,therock,The Rock,55.4M,13.1M,1.5M,14.3K,11.9K
8,bizarrap,bzrp,5.8M,16.2M,2.7M,4.2K,6.9K
9,landonbarkerr,Landon Barker,3.8M,11.7M,1.2M,19.1K,15.2K
10,mrbeast,MrBeast,42.2M,13M,1.7M,17.2K,2.1K
11,charlidamelio,charli dâ€™amelio,146.2M,15.2M,959.4K,20.8K,4.6K
12,amauryguichon,Amaury Guichon,14.5M,11.4M,1.5M,7.2K,11.8K
13,jetbentlee,Jet,3.9M,12.4M,2.2M,3.6K,6.6K
14,kervo.dolo,Kervo.dolo,10.3M,5.7M,1.3M,7.9K,27.6K
15,ttdramanews,TT Drama Layla,856.3K,6.1M,1.1M,16.6K,17.7K
16,mishayoung,ÐœÐ¸ÑˆÐ° Ð“Ð¾Ñ€Ð¾Ð´ÐµÑ†ÐºÐ¸Ð¹ ðŸ‡ºðŸ‡¦,4M,10.8M,680K,5.7K,22.5K
17,domelipa,domelipa,58.1M,10.4M,1.5M,9.1K,3.5K

In [12]:
Datos.shape

(1000, 7)

In [13]:
# Rellenar valores nulos
Nombres = Datos["Tiktok name"]
Datos_no_nulos = Datos["Tiktok name"].dropna().to_list()
for clave, valor in Nombres.items():
    if pd.isna(valor):
        indice = np.random.randint(0, len(Datos_no_nulos))
        Datos.at[clave, "Tiktok name"] = Datos_no_nulos[indice]
Datos.isnull().sum()

Tiktoker name    0
Tiktok name      0
Subscribers      0
Views avg.       0
Likes avg.       0
Comments avg.    0
Shares avg.      0
dtype: int64

In [14]:
# Guardar la informacion en un archivo CSV
Datos.to_csv(ruta_guardado_caso1+"Set_Datos.csv",index=False, encoding="utf-8")

In [15]:
# Guardar la informacion a una base de datos SQLite
conn = sqlite3.connect(ruta_guardado_caso1+"Social_Media_Tiktok.db")
cursor = conn.cursor()
Datos.to_sql(name="smi_tiktok", con=conn, if_exists="replace")
conn.commit()
# Gconn.close()

_Caso 6_

In [16]:
DatosC19_2=pd.read_csv(ruta_caso6+"COVID-19_County_Level_Data_-_Archive_20240301.csv", sep=",")
DatosC19_2.isnull().sum()

report_date                      0
county                           0
county_population              348
cumulative_cases                 0
cumulative_tests_reportable      0
cumulative_deaths                0
cases_7days                      0
tests_reportable_7days           0
positive_naat_7days              0
tests_naat_7days                 0
naat_positivity_7days          153
cumulative_positive_naat         0
cumulative_tests_naat            0
positive_ag_7days                0
census_today                   348
fullyvax_today                 348
partialvax_today               348
nonvax_today                   348
adddose_today                  348
census_7days_ago               348
census_change                  348
census_not_fully_vax           348
census_pct_not_fully_vax       539
case_rate_weekly               348
fips                           348
data_updated                     0
dtype: int64

In [17]:
Poblacion = DatosC19_2["county_population"]
Valores_no_nulos = Poblacion.dropna().to_list()
# Rellenar valores nulos
for clave, valor in Poblacion.items():
    if pd.isna(valor):
        indice = np.random.randint(0, len(Valores_no_nulos))
        DatosC19_2.at[clave, "county_population"] = Valores_no_nulos[indice]

# Verificar valores nulos
DatosC19_2.isnull().sum()

report_date                      0
county                           0
county_population                0
cumulative_cases                 0
cumulative_tests_reportable      0
cumulative_deaths                0
cases_7days                      0
tests_reportable_7days           0
positive_naat_7days              0
tests_naat_7days                 0
naat_positivity_7days          153
cumulative_positive_naat         0
cumulative_tests_naat            0
positive_ag_7days                0
census_today                   348
fullyvax_today                 348
partialvax_today               348
nonvax_today                   348
adddose_today                  348
census_7days_ago               348
census_change                  348
census_not_fully_vax           348
census_pct_not_fully_vax       539
case_rate_weekly               348
fips                           348
data_updated                     0
dtype: int64

In [18]:
Positividad = DatosC19_2["naat_positivity_7days"]
Valores_no_nulos = Positividad.dropna().to_list()
promedio = np.mean(Valores_no_nulos)  # Calculamos el promedio de los valores no nulos
# Rellenar valores nulos
for clave, valor in Positividad.items():
    if pd.isna(valor):
        DatosC19_2.at[clave, "naat_positivity_7days"] = promedio
# Verificar valores nulos
DatosC19_2.isnull().sum()

report_date                      0
county                           0
county_population                0
cumulative_cases                 0
cumulative_tests_reportable      0
cumulative_deaths                0
cases_7days                      0
tests_reportable_7days           0
positive_naat_7days              0
tests_naat_7days                 0
naat_positivity_7days            0
cumulative_positive_naat         0
cumulative_tests_naat            0
positive_ag_7days                0
census_today                   348
fullyvax_today                 348
partialvax_today               348
nonvax_today                   348
adddose_today                  348
census_7days_ago               348
census_change                  348
census_not_fully_vax           348
census_pct_not_fully_vax       539
case_rate_weekly               348
fips                           348
data_updated                     0
dtype: int64

In [19]:
CensoHoy = DatosC19_2["census_today"]
Valores_no_nulos = CensoHoy.dropna().to_list()
promedio = np.mean(Valores_no_nulos)  # Calculamos el promedio de los valores no nulos del DataFrame
# Rellenar valores nulos con el valor medio
for clave, valor in CensoHoy.items():
    if pd.isna(valor):
        DatosC19_2.at[clave, "census_today"] = promedio
# Verificar valores nulos
DatosC19_2.isnull().sum()

report_date                      0
county                           0
county_population                0
cumulative_cases                 0
cumulative_tests_reportable      0
cumulative_deaths                0
cases_7days                      0
tests_reportable_7days           0
positive_naat_7days              0
tests_naat_7days                 0
naat_positivity_7days            0
cumulative_positive_naat         0
cumulative_tests_naat            0
positive_ag_7days                0
census_today                     0
fullyvax_today                 348
partialvax_today               348
nonvax_today                   348
adddose_today                  348
census_7days_ago               348
census_change                  348
census_not_fully_vax           348
census_pct_not_fully_vax       539
case_rate_weekly               348
fips                           348
data_updated                     0
dtype: int64

In [20]:
vacunacionCompleta = DatosC19_2["fullyvax_today"]
Valores_no_nulos = vacunacionCompleta.dropna().to_list()
promedio = np.mean(Valores_no_nulos)  # Calculamos el promedio de los valores no nulos del DataFrame
# Rellenar valores nulos con el valor medio
for clave, valor in vacunacionCompleta.items():
    if pd.isna(valor):
        DatosC19_2.at[clave, "fullyvax_today"] = promedio
# Verificar valores nulos
DatosC19_2.isnull().sum()

report_date                      0
county                           0
county_population                0
cumulative_cases                 0
cumulative_tests_reportable      0
cumulative_deaths                0
cases_7days                      0
tests_reportable_7days           0
positive_naat_7days              0
tests_naat_7days                 0
naat_positivity_7days            0
cumulative_positive_naat         0
cumulative_tests_naat            0
positive_ag_7days                0
census_today                     0
fullyvax_today                   0
partialvax_today               348
nonvax_today                   348
adddose_today                  348
census_7days_ago               348
census_change                  348
census_not_fully_vax           348
census_pct_not_fully_vax       539
case_rate_weekly               348
fips                           348
data_updated                     0
dtype: int64

In [21]:
vacunasParciales = DatosC19_2["partialvax_today"]
Valores_no_nulos = vacunasParciales.dropna().to_list()
promedio = np.mean(Valores_no_nulos)  # Calculamos el promedio de los valores no nulos del DataFrame
# Rellenar valores nulos con el valor medio
for clave, valor in vacunasParciales.items():
    if pd.isna(valor):
        DatosC19_2.at[clave, "partialvax_today"] = promedio
# Verificar valores nulos
DatosC19_2.isnull().sum()

report_date                      0
county                           0
county_population                0
cumulative_cases                 0
cumulative_tests_reportable      0
cumulative_deaths                0
cases_7days                      0
tests_reportable_7days           0
positive_naat_7days              0
tests_naat_7days                 0
naat_positivity_7days            0
cumulative_positive_naat         0
cumulative_tests_naat            0
positive_ag_7days                0
census_today                     0
fullyvax_today                   0
partialvax_today                 0
nonvax_today                   348
adddose_today                  348
census_7days_ago               348
census_change                  348
census_not_fully_vax           348
census_pct_not_fully_vax       539
case_rate_weekly               348
fips                           348
data_updated                     0
dtype: int64

In [22]:
noVacunados = DatosC19_2["nonvax_today"]
Valores_no_nulos = noVacunados.dropna().to_list()
promedio = np.mean(Valores_no_nulos)  # Calculamos el promedio de los valores no nulos del DataFrame
# Rellenar valores nulos con el valor medio
for clave, valor in noVacunados.items():
    if pd.isna(valor):
        DatosC19_2.at[clave, "nonvax_today"] = promedio
# Verificar valores nulos
DatosC19_2.isnull().sum()

report_date                      0
county                           0
county_population                0
cumulative_cases                 0
cumulative_tests_reportable      0
cumulative_deaths                0
cases_7days                      0
tests_reportable_7days           0
positive_naat_7days              0
tests_naat_7days                 0
naat_positivity_7days            0
cumulative_positive_naat         0
cumulative_tests_naat            0
positive_ag_7days                0
census_today                     0
fullyvax_today                   0
partialvax_today                 0
nonvax_today                     0
adddose_today                  348
census_7days_ago               348
census_change                  348
census_not_fully_vax           348
census_pct_not_fully_vax       539
case_rate_weekly               348
fips                           348
data_updated                     0
dtype: int64

In [23]:
dosis = DatosC19_2["adddose_today"]
Valores_no_nulos = dosis.dropna().to_list()
promedio = np.mean(Valores_no_nulos)  # Calculamos el promedio de los valores no nulos del DataFrame
# Rellenar valores nulos con el valor medio
for clave, valor in dosis.items():
    if pd.isna(valor):
        DatosC19_2.at[clave, "adddose_today"] = promedio
# Verificar valores nulos
DatosC19_2.isnull().sum()

report_date                      0
county                           0
county_population                0
cumulative_cases                 0
cumulative_tests_reportable      0
cumulative_deaths                0
cases_7days                      0
tests_reportable_7days           0
positive_naat_7days              0
tests_naat_7days                 0
naat_positivity_7days            0
cumulative_positive_naat         0
cumulative_tests_naat            0
positive_ag_7days                0
census_today                     0
fullyvax_today                   0
partialvax_today                 0
nonvax_today                     0
adddose_today                    0
census_7days_ago               348
census_change                  348
census_not_fully_vax           348
census_pct_not_fully_vax       539
case_rate_weekly               348
fips                           348
data_updated                     0
dtype: int64

In [24]:
censo7dias = DatosC19_2["census_7days_ago"]
Valores_no_nulos = censo7dias.dropna().to_list()
promedio = np.mean(Valores_no_nulos)  # Calculamos el promedio de los valores no nulos del DataFrame
# Rellenar valores nulos con el valor medio
for clave, valor in censo7dias.items():
    if pd.isna(valor):
        DatosC19_2.at[clave, "census_7days_ago"] = promedio
# Verificar valores nulos
DatosC19_2.isnull().sum()

report_date                      0
county                           0
county_population                0
cumulative_cases                 0
cumulative_tests_reportable      0
cumulative_deaths                0
cases_7days                      0
tests_reportable_7days           0
positive_naat_7days              0
tests_naat_7days                 0
naat_positivity_7days            0
cumulative_positive_naat         0
cumulative_tests_naat            0
positive_ag_7days                0
census_today                     0
fullyvax_today                   0
partialvax_today                 0
nonvax_today                     0
adddose_today                    0
census_7days_ago                 0
census_change                  348
census_not_fully_vax           348
census_pct_not_fully_vax       539
case_rate_weekly               348
fips                           348
data_updated                     0
dtype: int64

In [25]:
cambioCenso = DatosC19_2["census_change"]
Valores_no_nulos = cambioCenso.dropna().to_list()
promedio = np.mean(Valores_no_nulos)  # Calculamos el promedio de los valores no nulos del DataFrame
# Rellenar valores nulos con el valor medio
for clave, valor in cambioCenso.items():
    if pd.isna(valor):
        DatosC19_2.at[clave, "census_change"] = promedio
# Verificar valores nulos
DatosC19_2.isnull().sum()

report_date                      0
county                           0
county_population                0
cumulative_cases                 0
cumulative_tests_reportable      0
cumulative_deaths                0
cases_7days                      0
tests_reportable_7days           0
positive_naat_7days              0
tests_naat_7days                 0
naat_positivity_7days            0
cumulative_positive_naat         0
cumulative_tests_naat            0
positive_ag_7days                0
census_today                     0
fullyvax_today                   0
partialvax_today                 0
nonvax_today                     0
adddose_today                    0
census_7days_ago                 0
census_change                    0
census_not_fully_vax           348
census_pct_not_fully_vax       539
case_rate_weekly               348
fips                           348
data_updated                     0
dtype: int64

In [26]:
sinVacunacioncompleta = DatosC19_2["census_not_fully_vax"]
Valores_no_nulos = sinVacunacioncompleta.dropna().to_list()
promedio = np.mean(Valores_no_nulos)  # Calculamos el promedio de los valores no nulos del DataFrame
# Rellenar valores nulos con el valor medio
for clave, valor in sinVacunacioncompleta.items():
    if pd.isna(valor):
        DatosC19_2.at[clave, "census_not_fully_vax"] = promedio
# Verificar valores nulos
DatosC19_2.isnull().sum()

report_date                      0
county                           0
county_population                0
cumulative_cases                 0
cumulative_tests_reportable      0
cumulative_deaths                0
cases_7days                      0
tests_reportable_7days           0
positive_naat_7days              0
tests_naat_7days                 0
naat_positivity_7days            0
cumulative_positive_naat         0
cumulative_tests_naat            0
positive_ag_7days                0
census_today                     0
fullyvax_today                   0
partialvax_today                 0
nonvax_today                     0
adddose_today                    0
census_7days_ago                 0
census_change                    0
census_not_fully_vax             0
census_pct_not_fully_vax       539
case_rate_weekly               348
fips                           348
data_updated                     0
dtype: int64

In [27]:
CensoSinvacunacion = DatosC19_2["census_pct_not_fully_vax"]
Valores_no_nulos = CensoSinvacunacion.dropna().to_list()
# Rellenar todos los valores nolos exiuente con el valor medio
promedio = np.mean(Valores_no_nulos)  # Calculamos el promedio de los valores no nulos del DataFrame
CensoSinvacunacion.fillna(promedio, inplace=True)  # Reemplazamos los valores NaN
# Verificar valores nulos
DatosC19_2.isnull().sum()

report_date                      0
county                           0
county_population                0
cumulative_cases                 0
cumulative_tests_reportable      0
cumulative_deaths                0
cases_7days                      0
tests_reportable_7days           0
positive_naat_7days              0
tests_naat_7days                 0
naat_positivity_7days            0
cumulative_positive_naat         0
cumulative_tests_naat            0
positive_ag_7days                0
census_today                     0
fullyvax_today                   0
partialvax_today                 0
nonvax_today                     0
adddose_today                    0
census_7days_ago                 0
census_change                    0
census_not_fully_vax             0
census_pct_not_fully_vax         0
case_rate_weekly               348
fips                           348
data_updated                     0
dtype: int64

In [28]:
rateoSemanal = DatosC19_2["case_rate_weekly"]
Valores_no_nulos = rateoSemanal.dropna().to_list()
promedio = np.mean(Valores_no_nulos)  # Calculamos el promedio de los valores no nulos del DataFrame
# Rellenar valores nulos con el valor medio
rateoSemanal.fillna(promedio, inplace=True)  # Reemplazamos los valores NaN
# Verificar valores nulos
DatosC19_2.isnull().sum()

report_date                      0
county                           0
county_population                0
cumulative_cases                 0
cumulative_tests_reportable      0
cumulative_deaths                0
cases_7days                      0
tests_reportable_7days           0
positive_naat_7days              0
tests_naat_7days                 0
naat_positivity_7days            0
cumulative_positive_naat         0
cumulative_tests_naat            0
positive_ag_7days                0
census_today                     0
fullyvax_today                   0
partialvax_today                 0
nonvax_today                     0
adddose_today                    0
census_7days_ago                 0
census_change                    0
census_not_fully_vax             0
census_pct_not_fully_vax         0
case_rate_weekly                 0
fips                           348
data_updated                     0
dtype: int64

In [29]:
fips = DatosC19_2["fips"]
Valores_no_nulos = fips.dropna().to_list()
promedio = np.mean(Valores_no_nulos)  # Calculamos el promedio de los valores no nulos del DataFrame
# Rellenar valores nulos con el valor medio
fips.fillna(promedio, inplace=True)  # Reemplazamos los valores NaN
# Verificar valores nulos
DatosC19_2.isnull().sum()

report_date                    0
county                         0
county_population              0
cumulative_cases               0
cumulative_tests_reportable    0
cumulative_deaths              0
cases_7days                    0
tests_reportable_7days         0
positive_naat_7days            0
tests_naat_7days               0
naat_positivity_7days          0
cumulative_positive_naat       0
cumulative_tests_naat          0
positive_ag_7days              0
census_today                   0
fullyvax_today                 0
partialvax_today               0
nonvax_today                   0
adddose_today                  0
census_7days_ago               0
census_change                  0
census_not_fully_vax           0
census_pct_not_fully_vax       0
case_rate_weekly               0
fips                           0
data_updated                   0
dtype: int64

Guardar el DataFrame en una base de datos MySQL

In [30]:
# Guardar el DataFrame en una base de datos MySQL
conn = ConexionMySQL() # Instanciar la clase ConexionMySQL para obtener la conexiÃ³n a BD
try:
    conectado = conn.Conexion(
        host="b7bg9l2v5kzw6mr8copl-mysql.services.clever-cloud.com", 
        user="ussbzqxxrbaktocd", 
        password="4jUZNEC8FPFOJasnBN7L", 
        db="b7bg9l2v5kzw6mr8copl"
    ) # Conectar a la base de datos
    if conectado:
        print("ConexiÃ³n exitosa")
        creacion = conn.Crear_tabla(dataframe=DatosC19_2, nombre_tabla="DatosC19") # Crear la tabla en la base de datos
        if creacion==0:
            print("Tabla creada en la base de datos MySQL")
            insercion = conn.Insertar_desde_dataframe(nombre_tabla="DatosC19", dataframe=DatosC19_2) # Insertar los registros en la tabla
            if insercion>0:
                print("Datos insertados en la tabla", "Filas afectadas:", insercion)
            else:
                print("No se insertaron los registros")
        else:
            print("No se creo la tabla")
    else:
        print("Error en la conexiÃ³n")
except Exception as e:
    print("Error al insertar los registros:", e)
finally:
    conn.Cerrar_conexion() # Cerrar la conexiÃ³n a la base de datos

ConexiÃ³n exitosa
Tabla creada en la base de datos MySQL
Datos insertados en la tabla Filas afectadas: 3132

In [31]:
# Guardar el DataFrame como archivo CSV
DatosC19_2.to_csv(ruta_guardado_caso6+"CasosCOVID.csv",index=False, encoding="utf-8")

_Siguiente Archivo_

In [32]:
DatosC19_3=pd.read_csv(ruta_caso6+"COVID-19_Vaccinations_by_Town_-_ARCHIVED_20240304.csv", sep=",")
DatosC19_3

,Town,At least one census tract SVIâ‰¥0.75,Population,Initiated Vaccination Count,Initiated Vaccination Percent,Fully Vaccinated Count,Fully Vaccinated Percent,Additional Dose 1 Received Count,Additional Dose 1 Received Percent,Date Updated
0,Address pending validation,NaN,NaN,14946,NaN,13110,NaN,NaN,NaN,12/01/2021
1,Andover,No,3236.0,2314,71.51,2161,66.78,NaN,NaN,12/01/2021
2,Ansonia,Yes,18654.0,12039,64.54,11083,59.41,NaN,NaN,12/01/2021
3,Ashford,No,4255.0,2886,67.83,2671,62.77,NaN,NaN,12/01/2021
4,Avon,No,18276.0,16327,89.34,14479,79.22,NaN,NaN,12/01/2021
...,...,...,...,...,...,...,...,...,...,...
16185,Windsor Locks,Yes,12854.0,9799,76.23,9200,71.57,5686.0,44.24,02/08/2023
16186,Wolcott,No,16587.0,12337,74.38,11769,70.95,6741.0,40.64,02/08/2023
16187,Woodbridge,No,8750.0,8376,95.73,7845,89.66,5542.0,63.34,02/08/2023
16188,Woodbury,No,9502.0,7688,80.91,7319,77.03,4806.0,50.58,02/08/2023
16189,Woodstock,No,7858.0,5907,75.17,5417,68.94,3232.0,41.13,02/08/2023

In [33]:
DatosC19_3.isnull().sum()

Town                                     0
At least one census tract SVIâ‰¥0.75     135
Population                             135
Initiated Vaccination Count              0
Initiated Vaccination Percent          135
Fully Vaccinated Count                   0
Fully Vaccinated Percent               135
Additional Dose 1 Received Count      6840
Additional Dose 1 Received Percent    6895
Date Updated                             0
dtype: int64

In [34]:
censoMayor = DatosC19_3["At least one census tract SVIâ‰¥0.75"]
Valores_no_nulos = censoMayor.dropna().to_list() #Elimino los valores nulos del DataFrame
for clave, valor in censoMayor.items():
    if pd.isna(valor):
        indice = np.random.randint(0, len(Valores_no_nulos))
        DatosC19_3.at[clave, "At least one census tract SVIâ‰¥0.75"] = Valores_no_nulos[indice]
# Verificar valores nulos
DatosC19_3.isnull().sum()

Town                                     0
At least one census tract SVIâ‰¥0.75       0
Population                             135
Initiated Vaccination Count              0
Initiated Vaccination Percent          135
Fully Vaccinated Count                   0
Fully Vaccinated Percent               135
Additional Dose 1 Received Count      6840
Additional Dose 1 Received Percent    6895
Date Updated                             0
dtype: int64

In [35]:
PorcentageInicial = DatosC19_3["Initiated Vaccination Percent"]
Valores_no_nulos = PorcentageInicial.dropna().to_list()
promedio = np.mean(Valores_no_nulos)  # Calculamos el promedio de los valores no nulos del DataFrame
# Rellenar todos los valores nulos con el valor medio
DatosC19_3.fillna(promedio, inplace=True)  # Reemplazamos los valores NaN
# Verificar valores nulos
DatosC19_3.isnull().sum()

Town                                  0
At least one census tract SVIâ‰¥0.75    0
Population                            0
Initiated Vaccination Count           0
Initiated Vaccination Percent         0
Fully Vaccinated Count                0
Fully Vaccinated Percent              0
Additional Dose 1 Received Count      0
Additional Dose 1 Received Percent    0
Date Updated                          0
dtype: int64

In [36]:
# Crear una cadena de conexiÃ³n
conexion = "mysql+mysqlconnector://ussbzqxxrbaktocd:4jUZNEC8FPFOJasnBN7L@b7bg9l2v5kzw6mr8copl-mysql.services.clever-cloud.com/b7bg9l2v5kzw6mr8copl"

# Crear un motor SQLAlchemy
engine = create_engine(conexion)

# Guardar el DataFrame en MySQL
tabla = "DatosCovid"
DatosC19_3.to_sql(tabla, con=engine, if_exists="replace", index=False)

-1

In [39]:
df = pd.concat([DatosC19_2, DatosC19_3])
df

,report_date,county,county_population,cumulative_cases,cumulative_tests_reportable,cumulative_deaths,cases_7days,tests_reportable_7days,positive_naat_7days,tests_naat_7days,...,Town,At least one census tract SVIâ‰¥0.75,Population,Initiated Vaccination Count,Initiated Vaccination Percent,Fully Vaccinated Count,Fully Vaccinated Percent,Additional Dose 1 Received Count,Additional Dose 1 Received Percent,Date Updated
0,06/16/2022,Fairfield,957418.0,224528.0,4072206.0,2745.0,913.0,11795.0,993.0,11682.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,06/16/2022,Hartford,899499.0,198162.0,3960442.0,3185.0,784.0,9312.0,736.0,9023.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,06/16/2022,Litchfield,185186.0,35092.0,725576.0,466.0,131.0,1595.0,127.0,1554.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,06/16/2022,Middlesex,164245.0,32402.0,922939.0,486.0,162.0,1942.0,190.0,1915.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,06/16/2022,New Haven,864835.0,214945.0,4420001.0,2866.0,873.0,13259.0,962.0,13114.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16185,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Windsor Locks,Yes,12854.0,9799.0,76.23,9200.0,71.57,5686.0,44.24,02/08/2023
16186,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Wolcott,No,16587.0,12337.0,74.38,11769.0,70.95,6741.0,40.64,02/08/2023
16187,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Woodbridge,No,8750.0,8376.0,95.73,7845.0,89.66,5542.0,63.34,02/08/2023
16188,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Woodbury,No,9502.0,7688.0,80.91,7319.0,77.03,4806.0,50.58,02/08/2023
16189,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Woodstock,No,7858.0,5907.0,75.17,5417.0,68.94,3232.0,41.13,02/08/2023